export const assignments = [
    {
      id: 1,
      category: "React Js",
      date: "06.02.2023",
      author: "Petrit Nuredini",
      jobPosition: "Software Engineer",
      title: "Create a React component",
      description: "Create a simple React component that displays a message on the screen. The message should be 'Hello World!'",
      details: [
        "Create a new file for your component, for example, 'HelloWorld.js'.",
        "Import React into your component file.",
        "Create a functional component that returns a div containing the message 'Hello World!'",
        "Export the component.",
        "Import the component into your main solution component and render it on the screen."
      ],
      difficulty: "Easy",
      averageTime: '2~4'
    },
    {
        id: 2,
        category: "React Js",
        date: "06.02.2023",
        author: "Petrit Nuredini",
        jobPosition: "Software Engineer",
        title: "Create a React component that displays a button",
        description: "Create a React component that displays a button. When the button is clicked, the text on the button should change to 'Clicked'",
        details:[
          "Create a new file for your component, for example, 'Button.js'",
          "Import React into your component file.",
          "Create a functional component that returns a button.",
          "Add an onClick event handler to the button that updates the component's state when the button is clicked.",
          "Use the component's state to dynamically render the text on the button.",
          "Export the component",
          "Import the component into your main solution component and render it on the screen."
        ],
        difficulty: "Easy",
        averageTime: '2~4'
      },
      {
        id: 3,
        category: "React Js",
        date: "06.02.2023",
        author: "Petrit Nuredini",
        jobPosition: "Software Engineer",
        title: "Create a React component that displays a list of numbers from 1 to 10",
        description: "Create a React component that displays a list of numbers from 1 to 10. The numbers should be displayed in a list format.",
        details: [
          "Create a new file for your component, for example, 'NumberList.js'",
          "Import React into your component file",
          "Create a functional component that returns a list",
          "Use a loop to dynamically create list items for each number from 1 to 10",
          "Export the component.",
          "Import the component into your main solution component and render it on the screen.",
        ],
        difficulty: "Easy",
        averageTime: '2~4'
      },
      {
        id: 4,
        category: "React Js",
        date: "06.02.2023",
        author: "Petrit Nuredini",
        jobPosition: "Software Engineer",
        title: "Create a React component that displays a form",
        description: "Create a React component that displays a form. The form should contain two text inputs for the user's first and last name, and a submit button. When the submit button is clicked, the form should display the full name of the user.",
        details: [
          "Create a new file for your component, for example, 'NameForm.js'",
          "Import React into your component file",
          "Create a class component with a constructor that sets the initial state for the first and last name",
          "Create a form with two text inputs and a submit button",
          "Use the onChange event handler to update the component's state as the user enters their first and last name",
          "Use the onSubmit event handler to display the full name of the user when the form is submitted.",
          "Export the component.",
          "Import the component into your main solution component and render it on the screen.",
        ],
        difficulty: "Easy",
        averageTime: '2~4'
      },
      {
        id: 5,
        category: "React Js",
        date: "06.02.2023",
        author: "Petrit Nuredini",
        jobPosition: "Software Engineer",
        title: "Create a React component that displays an image",
        description: "Create a React component that displays an image. The image should be sourced from a URL.",
        details: [
          "Create a new file for your component, for example, 'Image.js'",
          "Import React into your component file",
          "Create a functional component that returns an image element",
          "Set the source of the image to a URL",
          "Export the component.",
          "Import the component into your main solution component and render it on the screen.",
        ],
        difficulty: "asy",
        averageTime: '2~4'
      },
      {
        id: 6,
        category: "React Js",
        date: "06.02.2023",
        author: "Petrit Nuredini",
        jobPosition: "Software Engineer",
        title: "Create a React component that displays the current time",
        description: "Create a React component that displays the current time. The time should update every second.",
        details: [
          "Import the React library and use the useState and useEffect hooks",
          "Create a state variable to store the current time and set its initial value to the current date and time using new Date().",
          "Create an useEffect hook that updates the state every second using setInterval.",
          "Import the component into your main solution component and render it on the screen.",
          "Test the component to ensure that it is updating the time every second.",
        ],
        difficulty: "Medium",
        averageTime: '4~6',
      },
  ];